version: "3.9"

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${VMESS_PORT}:${VMESS_PORT}"
    volumes:
      - ./running.json:/etc/v2ray/config.json:ro
    command: ["run", "-c", "/etc/v2ray/config.json"]
